name: shahzaib

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get your Code
            - uses: actions/checkout@v2
            name: say Hello to the world Shahzaib Devops Engineer   
            run: echo " HELLO WORLD"