name: Greeting
on: push 
jobs:
      greeting:
        runs-on: ubuntu-latest
        steps:
          - name: Greeting
            run: echo "Hello, World!"
          - name: Greeting1
            run: echo "Hello, GitHub Actions!"
          - name: Greeting2
            run: echo "Hello, CI/CD!"
