name: shahzaib
on: push

jobs:
  build:
    runs-on: python-latest
    steps:
      - run: echo "Building the project"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Running tests"
