name: CI Workflow
on: push
jobs:
    build:
        runs-om: ubuntu-latest
        steps:
            - name: Checkoutcode
             uses: actions/checkout@v3
            - name: Run Tests
              run: npm test
              